# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 649456c865f1f9d8ebefcc4ce96f1ceeb214a6b5d9a6cdf00221b646d9fb597b8b4c4014fc263a14c691563498b1e191e1b0a2296bba2d0f9fe9d12a843740fa

test:
  secret_key_base: c99e53f96d78f0ce561d29f54362ca5ce0dc92cfb14fbe61471ad2395a13fa3bddb314a991c8c129df8888fab0afe60bf6044cba4a72cbb837aa8981e87e8bff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
